server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    add_header Access-Control-Allow-Origin "*";
    add_header X-Frame-Options SAMEORIGIN;

    location / {
        try_files $uri $uri/ /index.html;
        autoindex on;
    }

    location /health {
        return 200 "OK\n";
        add_header Content-Type text/plain;
    }
}
